services:
  order-service:
    image: gustavrosell69/orderserviceapi:latest
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - order-service
    ports:
    - "4000:4000"