name: Byg et Docker Image

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

jobs:
  docker_image_pipeline:
    name: Build Docker image to Docker Hub
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      IMAGE_NAME: catalog-service
      IMAGE_VERSION: 1.0.1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Get metadata from csproj-file
        uses: kzrnm/get-net-sdk-project-versions-action@v2
        id: get-version        
        with:
          proj-path: CatalogService.csproj 

      - name: Build the Docker image
        run: docker build . -f Dockerfile -t ${{env.DOCKER_USER }}/${{env.IMAGE_NAME }}:${{steps.get-version.outputs.informational-version}}

      - name: Push Docker image to Docker Hub
        run: docker push ${{env.DOCKER_USER}}/${{env.IMAGE_NAME}}:${{steps.get-version.outputs.informational-version}}
