services:

  userservice:
    image: gustavrosell69/user-service:1.0.1
    ports:
      - 5001:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoConnectionString=mongodb://admin:1234@mongodb:27017/1234?authSource=admin
      - DatabaseName=Users
      - CollectionName=userCollection

  mongodb:
    container_name: mongodb-1
    image: mongo:latest
    ports:
      - 27017:27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 1234

    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: