// <auto-generated />
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;

namespace Model
{
    public class User
    {
        /// <summary>
        /// Unique identifier for the user (MongoDB ObjectId)
        /// </summary>
        [BsonId]
        [BsonRepresentation(BsonType.ObjectId)]
        public string Id { get; set; }

        /// <summary>
        /// Unique identifier for the user
        /// </summary>
        [BsonElement("userId")]
        public string UserId { get; set; }

        /// <summary>
        /// First name of the user
        /// </summary>
        [BsonElement("givenName")]
        public string GivenName { get; set; }

        /// <summary>
        /// Last name of the user
        /// </summary>
        [BsonElement("familyName")]
        public string FamilyName { get; set; }

        /// <summary>
        /// User's password (with minimum length validation)
        /// </summary>
        [BsonElement("password")]
        public string Password { get; set; }

        /// <summary>
        /// User's email address
        /// </summary>
        [BsonElement("email")]
        public string Email { get; set; }
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
